/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Manulife.DNC.MSAD.Contracts
{
  public enum TrxnResult
  {
    SUCCESS = 0,
    FAILED = 1,
  }
}
